version: '3.8'

services:
  flow2api:
    image: thesmallhancat/flow2api:latest
    container_name: flow2api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config/setting.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
